### ISSUE TITLE
`journal_volume` has `B` as value after "journal letter split"

### ISSUE THREAD

**Issue by iulianav** [inspirehep/inspire-schemas#299] opened 2018-01-18 10:02 UTC
After migration, if on legacy the record had `B` as value in the marcxml `773__v` field, the inspire record ends up having `B` as well in `publication_info.journal_volume` and the letter does not get appended at the end of the journal_title.

Example record on legacy: http://inspirehep.net/record/205761 :+1: 
```
<datafield tag="773" ind1=" " ind2=" ">
<subfield code="p">Phys.Lett.</subfield>
<subfield code="v">B</subfield>
</datafield>
```

The resulting publication_info on labs is:
```
"publication_info": [
            {
              "journal_volume": "B",
              "journal_record": {
                "$ref": "http://localhost:5000/api/journals/1214521"
              },
              "journal_recid": 1214521,
              "journal_title": "Phys.Lett."
            }
          ],
```

**Comment by jacquerie** [comment] 2018-01-23 01:58
This was caused by bad data, not bugs in the code. So we decided to fix it by fixing the records on Legacy, as returned by the following query: https://inspirehep.net/search?p=773__v%3A%2F%5E%5BA-Za-z%5D%24%2F+and+773__p%3A**&wl=0. I don't know why https://inspirehep.net/record/1597324 appears to be fixed in the editor, but not in the MARCXML export. Any idea, @tsgit ?

**Comment by jacquerie** [comment] 2018-01-23 01:59
That said, I'm closing this because this was a data problem on Legacy, not a bug in `convert_old_publication_info_to_new` as I thought...

**Closed by jacquerie** 2018-01-23 01:59 UTC
Labels: bug

**Comment by tsgit** [comment] 2018-01-23 02:19
@jacquerie you have an editor session open, so it's possible you are looking at a version in bibedit-cache 

This record is being edited by user jacquerie (jacopo.notarstefano@cern.ch) since Jan 23, 02:54. Please try again later.

MARCXML I see is dated 2017-08-04
```
<datafield tag="773" ind1=" " ind2=" "><subfield code="p">Phil.Trans.Roy.Soc.Lond.</subfield><subfield code="v">A</subfield><subfield code="w">C17-03-18</subfield><subfield code="y">2017</subfield></datafield>
```

**Comment by tsgit** [comment] 2018-01-23 02:34
in fact I see in the data blob of the cached file
```
In [5]: cPickle.loads(run_sql('select data from bibEDITCACHE where id_bibrec=1597324')[0][0])[2]['773']
[([('0', 'VOLATILE:INSPIRE recid'), ('c', 'VOLATILE:firstpage-lastpage'), ('n', 'VOLATILE:issue'), ('p', 'Phil.Trans.Roy.Soc.Lond.A'), ('q', 'VOLATILE:conf acronym (if no CNUM exists)'), ('t', 'VOLATILE:name of conference (if no CNUM exists)'), ('v', 'VOLATILE:volume'), ('w', 'C17-03-18'), ('x', 'VOLATILE:freetext publication info'), ('y', '2017')], ' ', ' ', '', 46)]

```

**Comment by jacquerie** [comment] 2018-01-23 09:02
> you have an editor session open, so it's possible you are looking at a version in bibedit-cache

Ah, thanks, that was it! Now everything seems to be fixed.
